bookname: Lets-start-event-delivery
booktitle: イベント配信を始めよう!
review_version: 3.0
aut: [{name: "godan", file-as: "godan"}]
edt: ["godan"]
language: ja
toc: true
rights: (C) 2019　Studio Mocha
colophon: true
history:
  - - 2019-09-23 初版
prt: ねこのしっぽ
pbl: Studio Mocha
edt: Studio Mocha
secnolevel: 3
titlepage: true
review_version: 3
texstyle:
  - reviewmacro
texdocumentclass:
  - review-jsbook
  - >-
    media=ebook,paper=b5,serial_pagination=true,hiddenfolio=nikko-pc,openany,fontsize=10pt,baselineskip=15.4pt,line_length=40zw,number_of_lines=35,head_space=30mm,headsep=10mm,headheight=5mm,footskip=10mm
